import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import SessionProvider from '@/providers/SessionProvider';
import Layout from '@/components/Layout';
import '../../globals.css';
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';
import TranslationsProvider from '@/providers/TranslationsProvider';
import initTranslations from '@/app/i18n';
import { i18nNamespaces } from '@/constant/const';
import CookieProvider from '@/providers/CookieProvider';
import Script from 'next/script';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin']
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default async function RootLayout({
    children,
    params
}: {
    children: React.ReactNode;
    params: { locale: string };
}) {
    const { locale } = await params;
    const { resources } = await initTranslations(locale);
    // Kiểm tra đăng nhập bằng cookie hoặc session
    const cookieStore = await cookies();
    const authToken = cookieStore.get('next-auth.session-token')?.value;

    // Nếu có token, chuyển hướng đến trang chủ
    if (authToken) {
        redirect(`/${locale}`);
    }
    return (
        <html lang={locale} className="h-full" suppressHydrationWarning>
            <head>
                <Script id="theme-script-auth" strategy="beforeInteractive">
                    {`
                    (function() {
                        try {
                            const savedTheme = localStorage.getItem('theme');
                            if (savedTheme) {
                                document.documentElement.setAttribute('data-theme', savedTheme);
                            } else if (window.matchMedia && window.matchMedia('(prefers-color-scheme: light)').matches) {
                                document.documentElement.setAttribute('data-theme', 'light');
                            } else {
                                document.documentElement.setAttribute('data-theme', 'dark');
                            }
                        } catch (e) {
                            console.error('Error applying theme:', e);
                            document.documentElement.setAttribute('data-theme', 'dark');
                        }
                    })();
                    `}
                </Script>
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
                suppressHydrationWarning
            >
                <ToastContainer
                    position="top-right"
                    autoClose={3000}
                    hideProgressBar={false}
                    newestOnTop
                    closeOnClick
                    rtl={false}
                    pauseOnFocusLoss
                    draggable
                    pauseOnHover
                    theme="dark"
                />
                <CookieProvider>
                    <SessionProvider>
                        <TranslationsProvider
                            namespaces={i18nNamespaces}
                            locale={locale}
                            resources={resources}
                        >
                            <main className="h-full w-full">
                                <Layout isHeader={false}>{children}</Layout>
                            </main>
                        </TranslationsProvider>
                    </SessionProvider>
                </CookieProvider>
            </body>
        </html>
    );
}
